apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
  name: neo4j-service
  namespace: default
spec:
  ports:
  - name: 7474-to-7474-tcp
    nodePort: 31716
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: 7473-to-7473-tcp
    nodePort: 32375
    port: 7473
    protocol: TCP
    targetPort: 7473
  - name: 7687-to-7687-tcp
    nodePort: 31182
    port: 7687
    protocol: TCP
    targetPort: 7687
  selector:
    app: neo4j
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pv-claim
  labels:
    app: magento2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: neo4j
  name: neo4j
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - image: asia.gcr.io/hermitcrab-217412/neo4j
        imagePullPolicy: Always
        name: neo4j
        volumeMounts:
        - name: neo4j-persistent-storage
          mountPath: /data
      volumes:
      - name: neo4j-persistent-storage
        persistentVolumeClaim:
          claimName: neo4j-pv-claim